enum data_entries_floats {
	FREQUENCY_GHZ, TEMPERATURE_K, AEFF_UM, MAX_DIMENSION_MM,
	CABS_M, CBK_M, CEXT_M, CSCA_M, G,
	AS_XY,
	NUM_DATA_ENTRIES_FLOATS
};
enum data_entries_ints {
	FLAKETYPE,
	NUM_DATA_ENTRIES_INTS
};
enum data_entries_stats_fields {
	S_MIN, S_MAX, MEDIAN, MEAN, SD, SKEWNESS, KURTOSIS,
	NUM_DATA_ENTRIES_STATS
};


