
set (srcfiles
	src/absorb.cpp
	src/absorber.cpp
	src/atmos.cpp
	src/atmoslayer.cpp
	src/bhmie.cpp
	src/chebyshev.cpp
	src/command.cpp
	src/config.cpp
	src/coords.cpp
	src/daDiagonalMatrix.cpp
	src/daInitLayer.cpp
	src/daLayer.cpp
	src/damatrix.cpp
	src/damatrix_quad.cpp
	src/daPf.cpp
	src/daStatic.cpp
	src/ddLoader.cpp
	src/ddOutput.cpp
	src/ddOutputEnsemble.cpp
	src/ddOutputMie.cpp
	src/ddOutputSingle.cpp
	src/ddpar.cpp
	src/ddscat.cpp
	src/ddScattMatrix.cpp
	src/ddweights.cpp
	src/debug.cpp
	src/debug_mem.cpp
	src/emd.cpp
	src/error.cpp
	src/gridCDF.cpp
	src/gridded.cpp
	src/gridStatic.cpp
	src/hermite.cpp
	src/interpolatable.cpp
	src/laguerre.cpp
	src/legendre.cpp
	src/matrixop.cpp
	src/matrixop-ipp.cpp
	src/mie-abNCalc.cpp
	src/mie-AnCalc.cpp
	src/mie-phaseFunc.cpp
	src/mie-piNCalc.cpp
	src/mie-Qcalc.cpp
	src/mie-Scalc.cpp
	src/mieScattMatrix.cpp
	src/mie-tauNCalc.cpp
	src/mie-wnCalc.cpp
	src/mtab.cpp
	src/MurmurHash3.cpp
	src/ncContainer.cpp
	src/os_functions.cpp
	src/pfFixed.cpp
	src/phaseFunc.cpp
	src/polynomial.cpp
	src/Qcalc-Rayleigh.cpp
	src/quadrature.cpp
	src/rayleighPhaseFunc.cpp
	src/recursivePolynomial.cpp
	src/refract.cpp
	src/ROOT_functions.cpp
	src/rtmath.cpp
	src/Scalc-Rayleigh.cpp
	src/shapefile.cpp
	src/Stdafx.cpp
	src/surfaces.cpp
	src/thermal.cpp
	src/units.cpp
	src/zeros.cpp
)

