/********************************************************************
* out.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error out.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern G__DLLEXPORT int G__cpp_dllrevout();
extern G__DLLEXPORT void G__set_cpp_environmentout();
extern G__DLLEXPORT void G__cpp_setup_tagtableout();
extern G__DLLEXPORT void G__cpp_setup_inheritanceout();
extern G__DLLEXPORT void G__cpp_setup_typetableout();
extern G__DLLEXPORT void G__cpp_setup_memvarout();
extern G__DLLEXPORT void G__cpp_setup_globalout();
extern G__DLLEXPORT void G__cpp_setup_memfuncout();
extern G__DLLEXPORT void G__cpp_setup_funcout();
extern G__DLLEXPORT void G__cpp_setupout();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "ddOutputSingleTrees.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__outLN_TClass;
extern G__linked_taginfo G__outLN_TBuffer;
extern G__linked_taginfo G__outLN_TMemberInspector;
extern G__linked_taginfo G__outLN_TObject;
extern G__linked_taginfo G__outLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__outLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__outLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR;
extern G__linked_taginfo G__outLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__outLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__outLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__outLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR;
extern G__linked_taginfo G__outLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__outLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__outLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__outLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__outLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__outLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__outLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__outLN_ddOutputSingleTreeBranch;

/* STUB derived class for protected member access */
