SET (UDUNITS2_INCLUDE_SEARCH_DIRS
	$ENV{UDUNITS2_INSTALL}/include
	$ENV{UDUNITS2_INSTALL}/include/udunits2
    /usr/include
    /usr/include/udunits2
)
SET (UDUNITS2_LIBRARIES_SEARCH_DIRS
	$ENV{UDUNITS2_INSTALL}/lib64
	$ENV{UDUNITS2_INSTALL}/lib
	/usr/lib64
	/usr/lib
)

find_library(UDUNITS2_LIBRARIES NAMES udunits2
	PATHS ${UDUNITS2_LIBRARIES_SEARCH_DIRS}
	)
find_path(UDUNITS2_INCLUDE_DIR NAMES udunits2.h
	PATHS ${UDUNITS2_INCLUDE_SEARCH_DIRS})
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(UDUNITS2 DEFAULT_MSG UDUNITS2_LIBRARIES UDUNITS2_INCLUDE_DIR)

mark_as_advanced(
	UDUNITS2_LIBRARIES
	UDUNITS2_INCLUDE_DIR
	)

